#WDI - WORLD DEVELOPMENT INDICATORS
#É A BASE DE DADOS DO BANCO MUNDIAL

#install.packages("WDI")
library(WDI)

#SEMPRE PROCUREM AS VIGNETTES
#QUE SÃO PÁGINAS COM ORIENTAÇÕES DOS PACOTES

#GDP- GROSS DOMESTIC PRODUCT- É O PIB
#BAIXAR OS DADOS DO PIB (PRODUTO INTERNO BRUTO)
#TUDO QUE É PRODUZIDO EM UM PAÍS/ESTADO/MUNICÍPIO
#EM UM DETERMINADO PERÍODO

#GDP (current US$)(NY.GDP.MKTP.CD)
#GROSS DOMESTIC PRODUCT(GDP) EM DÓLARES NORTE-AMERICANOS
#CÓDIGO NY.GDP.MKTP.CD

COD_GDP<-WDIsearch('gdp')
#É IMPORTANTE PROCURAR PELO PRÓPIO SITE DO BANCO MUNDIAL
#NO SITE TEM 89 VARIÁVEIS DISPONÍVEIS PRA VER
#NO R, PUXOU 540 OBSERVAÇÕES, TEM COISA SEM SENTIDO NO MEIO

basepib <- WDI(country = 'all', 
               indicator = 'NY.GDP.MKTP.CD')


#COM O CÓDIGO, VAMOS BAIXAR OS DADOS               

options(scipen=999) #AJUSTAR NÚMEROS(NOT. CIENTI.)          
basepib <- WDI(country = 'all',
               indicator = 'NY.GDP.MKTP.CD')


#QUAL O MAIOR PIB DO MUNDO EM 2023
basepib2023 <- WDI(country = 'all',
                   indicator = 'NY.GDP.MKTP.CD',
                   start = 2023, end = 2023)
  